name: Update Discord Widgets

on:
  repository_dispatch:
    types: [update-widget]
  workflow_dispatch:

jobs:
  update-widget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Run script
        env:
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          
          HC_DISCORD_APP_ID: ${{ secrets.HC_DISCORD_APP_ID }}
          HC_DISCORD_BOT_TOKEN: ${{ secrets.HC_DISCORD_BOT_TOKEN }}
          HARDCOVER_API_KEY: ${{ secrets.HARDCOVER_API_KEY }}
        run: |
          node anilist.js
          node hardcover.js
